[package]
name = "duckdb_age_crypto"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
age = "0.11"
secrecy = "0.10"
x25519-dalek = "2.0"
rand = "0.8"
sha2 = "0.10"
rand_chacha = "0.3"